### ISSUE TITLE
RFC: UI for DFKQuestRunner

### ISSUE THREAD

**Issue by dayhaysoos** [SansegoTek/DFKQuestRunner#12]
# Overview

@SansegoTek kicked of DFKQuestRunner, a tool that runs DFK quests for you without needing to log in and do it yourself. As of right now, the tool is only available to use by anyone with a little bit of developer experience.

It would be ideal to create a UI on top of DFKQuestRunner that would allow many to take advantage of what it has to offer. This RFC is a high-level proposal for how this can be achieved. Any and all feedback is welcome.

The goals from the UI would be to have the following:
- Connect to site through MM wallet to allow access to API
- Display heroes and select which ones you'd like to run quests with
- Run optimal quests based on hero professions
- Provide a way to run quests however you want 
- Display state to keep user up to date on progress

# Proposal

NextJS is the leading framework for full-stack React apps. This tool is already built with node so it won't be too hard to switch most of it over.

With React, we can create some easy-to-use hooks that can be passed around throughout the app that also manage things that we need like loading states.

For example, the hook would be called `useRunner`  or`useQuests` if we want to be more specific and intentional about the API we're using.

Consider the following code:

```js
  import React from 'react'
  import { useQuest } from '../hooks/useQuest'

function QuestRunner() {
  const { startQuest } = useQuest()

  return (
    <>
      // Quest Runner UI here
       <button onPress={() => startQuest(FISHING_QUEST_ID_HERE)}>Fishing Quest</button>
    </>
  )
}
```

I think it'd be better to have a UI for selecting and managing the configuration of the quest runner, but the point of this example code was to show how the hooks would be used.

We'd need state management to handle setting up the configuration of using the quest runner, we don't need a library or anything. Could probably get far enough with `useReducer`. Here are some of the things we'd have to manage as far as state, this reflects what's in the current config file for DFKrunner:

- Quests
- Profession Heroes
- Non Profession Heroes

## Styling
Not sure how people feel here, perhaps we can stick to Tailwind (I've never used Tailwind)

## Note

Not sure how signing into Meta Mask would work here, someone should definitely speak on that if they're familiar. Perhaps we can make a kind of <QuestProvider /> for local usage until we have that figured out. Let me know if you'd like for me to elaborate on that.

# How to provide feedback

This RFC is open to feedback, let me know if I've forgotten anything. If we come to an agreement on things, I wouldn't mind kicking  off the foundation.

**Comment by bhchiang** [comment]
Great idea, one tricky thing I see is how can we automate new transactions on behalf of a user without needing raw access to the user's private key. Until then it'd probably have to be some sort of local Electron app, but even that would be very helpful.
