### ISSUE TITLE
"quest is not ready to start"

### ISSUE THREAD

**Issue by peterbaker** [SansegoTek/DFKQuestRunner#18]
I don't get errors, but I don't see it working either.

No matter how I config the heroes, I get these messages, no matter how much stamina by heroes have:

```
Non-professional Fishing quest is not ready to start.
Non-professional Foraging quest is not ready to start.
```

**Comment by leunamd** [comment]
Have you tried setting the "useBackupRpc" setting to true?
It seems like the official Harmony RPC has been having problems

**Comment by SansegoTek** [comment]
How many non-professional attempts do you have configured? Needs to be three or under otherwise the stamina requirement will be too high

**Comment by peterbaker** [comment]
> How many non-professional attempts do you have configured? Needs to be three or under otherwise the stamina requirement will be too high

Just as it was out of the box:

```
"professionMaxAttempts": 5,
"nonProfessionMaxAttempts": 3,
"maxQuestGroupSize": 6,
```

**Comment by peterbaker** [comment]
Actually it appears is has been working? Just checked in the browser and stamina has gone down and fish have been caught. So just not showing any success in the terminal?

**Comment by peterbaker** [comment]
Actually I did see it work one when i scrolled back in the terminal. But my heroes have plenty of stamina and it's not sending them on quests currently...

**Comment by peterbaker** [comment]
Does it wait until they have enough stamina for multiple attempts?

**Comment by SansegoTek** [comment]
Yep, that’s controlled by the maxAttempts settings. E.g. if professionMaxAttempts is set to 5 then it will wait til stamina of those heroes is up to 25.

**Comment by peterbaker** [comment]
Ok, makes sense now. My bad.
